In [23]:
import numpy as np

In [24]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1.0, 2.0, 3.0, 4.0, 5.0], [-1.0, -2.0, -3.0, -4.0, -5.0]])

In [25]:
print(b.shape)
print(b.dtype)
print(a.dtype)


(2, 5)
float64
int64


In [26]:
zeros = np.zeros((3,3))
ones = np.ones((2,4))
full = np.full((3, 6), 12)
grid = np.arange(0, 10, 2)
lin = np.linspace(0, 1, 5)

In [19]:
print(grid)
print(lin)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [20]:
print(grid + lin)
print(grid * lin)
print(lin ** 2)
print(np.sin(lin))
print(np.dot(grid, lin))

[0.   2.25 4.5  6.75 9.  ]
[0.  0.5 2.  4.5 8. ]
[0.     0.0625 0.25   0.5625 1.    ]
[0.         0.24740396 0.47942554 0.68163876 0.84147098]
15.0


In [14]:
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)*np.exp(-x/5)
print(y.mean(), y.max())

0.10834615024732402 0.7448581273793697


In [35]:
t = np.linspace(0, 10, 1000)
y_1 = np.sin(t)
y_2 = np.cos(t)
y_3 = y_1 + np.random.normal(0, 0.1, 1000)
data = np.column_stack((t, y_1, y_3))
np.savetxt("experiment_data.csv", data, delimiter = ",", fmt = "%.3f", header = "time,clean_signal,noisy_signal")
t_read, y_1_read, y_3_read = np.loadtxt("experiment_data.csv", delimiter = ",", skiprows = 1, unpack = True)
np.save('big_array.npy', np.column_stack((t_read, y_1_read, y_3_read)))
restored_arr = np.load('big_array.npy')
np.savez('lab_results.npz', time = t, sin = y_1, cos = y_2, noisy = y_3)
data_pack = np.load('lab_results.npz')
print(data_pack.files)
print(data_pack['cos'].shape)

['time', 'sin', 'cos', 'noisy']
(1000,)


In [39]:
a = np.array([[2.0, 3.0], [4.0, -1.0]])
b = np.array([8.0, 2.0])
x = np.linalg.solve(a, b)
print(a @ x)
print(np.linalg.det(a))
a_inv = np.linalg.inv(a)
print(a_inv)
s = np.array([[2, 1],[3, 15]])
values, vectors = np.linalg.eig(s)
print(values)
print(vectors)

[8. 2.]
-14.000000000000004
[[ 0.07142857  0.21428571]
 [ 0.28571429 -0.14285714]]
[ 1.77318798 15.22681202]
[[-0.97522986 -0.07538885]
 [ 0.22119386 -0.99715421]]


In [41]:
a = np.array([[1, 2, 1],[3, -5, 2], [2, 7, -1]])
b = np.array([4, 1, 8])
x = np.linalg.solve(a, b)
print(np.linalg.norm(x))

1.8008485654145259


In [50]:
rng = np.random.default_rng(seed=67)
uniform_data = rng.uniform(0, 10, 100)
normal_data = rng.normal(5, 1, 100)
arr = np.array([1, 2, 3, 4, 5, 6])
sample = rng.choice(arr, 3, replace = True)
print(sample)

[4 4 5]


In [51]:
data = np.array(['cat', 'dog', 'cat', 'bird', 'dog', 'cat'])
values, count = np.unique(data, return_counts = True)
print(values)
print(count)

['bird' 'cat' 'dog']
[1 3 2]


In [56]:
scores = rng.normal(170, 10, 1000)
counts, bin_edges = np.histogram(scores, 10)
print(counts)
print(bin_edges)

[ 12  32  89 213 252 214 133  47   7   1]
[140.42448095 146.83632994 153.24817892 159.66002791 166.07187689
 172.48372588 178.89557487 185.30742385 191.71927284 198.13112182
 204.54297081]
